title: 자기소개서
description: Long Form Jekyll theme built with SASS

url: https://didfodms.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Velog
    url: /velog

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com
  linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
  shortname: brianmaierjr
