title:
description: Long Form Jekyll theme built with SASS

baseurl: /blog
url: https://didfodms.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Velog
    url: /velog

social:
  github: didfodms
  # twitter: brianmaierjr
  # facebook: brianmaierjr
  email: didfodms@gmail.com
  instagram: rae___eun
  # linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
  shortname: brianmaierjr
